<?php

return [
    'ONEPAY_DOMAIN' => env('ONEPAY_DOMAIN'),
    'ONEPAY_VPCURL' => env('ONEPAY_VPCURL'),
    'ONEPAY_VPC_MERCHANT' => env('ONEPAY_VPC_MERCHANT'),
    'ONEPAY_VPC_ACCESSCODE' => env('ONEPAY_VPC_ACCESSCODE'),
    'ONEPAY_SECURE_SECRET' => env('ONEPAY_SECURE_SECRET'),
    'ONEPAY_VPC_MERCHANT_TG' => env('ONEPAY_VPC_MERCHANT_TG'),
    'ONEPAY_VPC_ACCESSCODE_TG' => env('ONEPAY_VPC_ACCESSCODE_TG'),
    'ONEPAY_SECURE_SECRET_TG' => env('ONEPAY_SECURE_SECRET_TG'),
    'code_bank' => [
        'SACLVNVX' => 'SCB',
        'BIDVVNVX' => 'BIDV',
        'SGTTVNVX' => 'Sacombank',
        'VNIBVNVX' => 'VIB',
        'MSCBVNVX' => 'MB Bank',
        'SHBAVNVX' => 'SHB',
        'VPBKVNVX' => 'VPBank',
        'VTCBVNVX' => 'Techcombank',
        'MCOBVNVX' => 'MaritimeBank',
        'SEAVVNVX' => 'SeABank',
        'SHBKVNVX' => 'SHINHAN Bank',
        'NAMAVNVX' => 'Nam A Bank',
        'HSBCVNVX' => 'HSBC',
        'TPBVVNVX' => 'TP Bank',
        'SCBLVNVX' => 'Standard Chartered',
        'BFTVVNVX' => 'VietcomBank',
        'EBVIVNVX' => 'Eximbank',
        'ORCOVNVX' => 'OCB',
        'KLBKVNVX' => 'Kienlongbank',
        'ASCBVNVX' => 'ACB',
        'ICBVVNVX' => 'VietinBank',
        'ABBKVNVX' => 'ABBank',
        'VPBKVNVXFE' => 'FE CREDIT',

        'VNACVNVX' => 'VietABank',
        'HDBCVNVX' => 'HDBank',
        'EACBVNVX' => 'DongA Bank',
        'OJBAVNVX' => 'OCEANBANK',
        'NASCVNVX' => 'NASB',
        'NVBAVNVX' => 'NCB',
        'VBAAVNVX' => 'Agribank',
        'WBVNVNVX' => 'PVcomBank',
        'VCBCVNVX' => 'VCCB (Bản Việt)',
        'GBNKVNVX' => 'GPBank',
        'LVBKVNVX' => 'LienVietPostBank',
        'BVBVVNVX' => 'BVB',
        'VRBAVNVX' => 'VRB',
        'VIDPVNV5' => 'PBVN',
        'SBITVNVX' => 'Saigon Bank',
        'PGBLVNVX' => 'PG Bank',
        'IABBVNVX' => 'IVB',
        'HVBKVNVX' => 'Woori Bank',
        'UOVBVNVX' => 'UOB',
    ],
];
